### PR TITLE
Changed next button to submit button on the last step

### PR DESCRIPTION
**Pull request by DimK10**
When a form is used with this component, there must be an onSubmit function on the last step, to handle all the form data and to make a request to an api, so i added this functionality.

### CODE REVIEW

**Comment by saini-g** [comment]
@DimK10 there is a conflict in the code, please resolve it and then I will merge

**Comment by DimK10** [comment]
I have resolved all the conflicts, so it's good to go. Please, if possible, make the necessary actions so that i can use the updated code in the npm (in order to use the code with the commit that fixed the stroke-width error, i needed to npm i https://github.com/saini-g/react-step-progress.git to get the code directly from master, the npm i 
react-step-progress is not updated). Also, thanks!

**Comment by saini-g** [comment]
@DimK10 
Really glad you like the component.

> i could change the readme for the documentation with the changes applied. 

That would be awesome. I can get the new release on npm easily over the weekend.

**Comment by DimK10** [comment]
Cool! I'll make another commit with the readme changes for the documentation! Feel free to contact me in dimk10@hotmail.com
if you want anything else

**Comment by DimK10** [comment]
The branch is ready to merge! I also made the necessary fixes in the readme.md file.

**Pull request merged**
